image:
  repository: docker.io/percona/pmm-server

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix

secret:
  name: pmm-secret
  create: true
  
storage:
  storageClassName: "oci-bv"
  size: 50Gi