istiod: 
  defaults:
    meshConfig:
      enablePrometheusMerge: true
      accessLogFile: /dev/stdout
      pathNormalization:
        normalization: MERGE_SLASHES
      defaultConfig:
        proxyMetadata:
          ISTIO_META_IDLE_TIMEOUT: 0s
        holdApplicationUntilProxyStarts: true
        gatewayTopology:
          numTrustedProxies: 2
      extensionProviders:
      - name: oauth2-proxy
        envoyExtAuthzHttp:
          service: oauth2-proxy.oauth2-proxy.svc.cluster.local
          port: 80
          headersToDownstreamOnDeny:
          - content-type
          - set-cookie
          headersToUpstreamOnAllow:
          - authorization
          - path
          - x-auth-access-token
          - x-auth-request-user
          - x-auth-request-email
          - x-auth-request-preferred-username
          - x-auth-request-groups
          includeAdditionalHeadersInCheck:
            X-Auth-Request-Redirect: https://%REQ(:authority)%%REQ(:path)%
          includeRequestHeadersInCheck:
          - authorization
          - cookie